# Generated by Django 6.0.5 on 2026-06-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciberseguranca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('responsavel_seguranca', models.CharField(max_length=100)),
                ('contacto_emergencia', models.CharField(max_length=20)),
                ('classificacao_seguranca', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
                ('estado_nis2', models.CharField(choices=[('Conforme', 'Conforme'), ('Em avaliação', 'Em avaliação'), ('Com pendências', 'Com pendências')], max_length=30)),
            ],
        ),
    ]
