# Generated by Django 6.0.5 on 2026-06-02 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciberseguranca', '0002_organizacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilizadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciberseguranca.organizacoes')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciberseguranca.role')),
            ],
        ),
    ]
