# Generated by Django 6.0.5 on 2026-06-02 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciberseguranca', '0004_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao_suporte', models.TextField()),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta'), ('Crítica', 'Crítica')], max_length=20)),
                ('estado_resolucao', models.CharField(choices=[('Aberto', 'Aberto'), ('Em análise', 'Em análise'), ('Resolvido', 'Resolvido'), ('Fechado', 'Fechado')], max_length=30)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciberseguranca.categorias')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciberseguranca.organizacoes')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciberseguranca.utilizadores')),
            ],
        ),
    ]
