# Generated by Django 6.0.5 on 2026-06-02 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciberseguranca', '0005_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_mensagem', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciberseguranca.tickets')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciberseguranca.utilizadores')),
            ],
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('ficheiro', models.FileField(upload_to='documentos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciberseguranca.tickets')),
            ],
        ),
    ]
