# Generated by Django 6.0.5 on 2026-06-02 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciberseguranca', '0006_chats_documentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembretes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('data_lembrete', models.DateTimeField()),
                ('concluido', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciberseguranca.tickets')),
            ],
        ),
    ]
