# Generated by Django 6.0.5 on 2026-06-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciberseguranca', '0007_lembretes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registos_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_registo', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciberseguranca.tickets')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciberseguranca.utilizadores')),
            ],
        ),
    ]
